# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-16 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('short_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Short name')),
                ('stadium', models.CharField(blank=True, max_length=250, null=True, verbose_name='Stadium')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('description', models.TextField(max_length=750)),
            ],
            options={
                'verbose_name': 'League',
                'verbose_name_plural': 'Leagues',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team_odds', models.FloatField(blank=True, null=True, verbose_name='Home team odds')),
                ('away_team_odds', models.FloatField(blank=True, null=True, verbose_name='Away team odds')),
                ('match_date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('match_time', models.TimeField(blank=True, null=True, verbose_name='Time')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BetProsApp.League', verbose_name='League')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Match Result',
                'verbose_name_plural': 'Match Results',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250, verbose_name='Name')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Name')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Sport',
                'verbose_name_plural': 'Sports',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='prediction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='BetProsApp.MatchResult', verbose_name='Prediction'),
        ),
        migrations.AddField(
            model_name='match',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='BetProsApp.MatchResult', verbose_name='Result'),
        ),
        migrations.AddField(
            model_name='league',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BetProsApp.Region', verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='league',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BetProsApp.Sport', verbose_name='Sport'),
        ),
        migrations.AddField(
            model_name='club',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BetProsApp.League', verbose_name='League'),
        ),
    ]
