# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-16 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetProsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='icon',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Icon'),
        ),
        migrations.AddField(
            model_name='sport',
            name='image',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Image'),
        ),
    ]
