# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-16 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetProsApp', '0004_remove_sport_sport_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='sport_image',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='Sport Image'),
        ),
    ]
