# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-16 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BetProsApp', '0006_remove_sport_sport_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='BetProsApp.Club', verbose_name='Away Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='BetProsApp.Club', verbose_name='Home Team'),
        ),
    ]
