# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-16 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetProsApp', '0008_auto_20170916_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='in_popular_list',
            field=models.BooleanField(default=False, verbose_name='In popular list'),
        ),
    ]
