# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-16 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetProsApp', '0009_league_in_popular_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='description',
            field=models.TextField(blank=True, max_length=750, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Description'),
        ),
    ]
