# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-16 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BetProsApp', '0010_auto_20170916_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Complete'),
        ),
    ]
